// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.google.protobuf;

public final class ApiProto {
  private ApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_Api_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Method_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_Method_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Mixin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_Mixin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapi.proto\022\017google.protobuf\032$google/pro" +
      "tobuf/source_context.proto\032\032google/proto" +
      "buf/type.proto\"\201\002\n\003Api\022\014\n\004name\030\001 \001(\t\022(\n\007" +
      "methods\030\002 \003(\0132\027.google.protobuf.Method\022(" +
      "\n\007options\030\003 \003(\0132\027.google.protobuf.Option" +
      "\022\017\n\007version\030\004 \001(\t\0226\n\016source_context\030\005 \001(" +
      "\0132\036.google.protobuf.SourceContext\022&\n\006mix" +
      "ins\030\006 \003(\0132\026.google.protobuf.Mixin\022\'\n\006syn" +
      "tax\030\007 \001(\0162\027.google.protobuf.Syntax\"\325\001\n\006M" +
      "ethod\022\014\n\004name\030\001 \001(\t\022\030\n\020request_type_url\030" +
      "\002 \001(\t\022\031\n\021request_streaming\030\003 \001(\010\022\031\n\021resp" +
      "onse_type_url\030\004 \001(\t\022\032\n\022response_streamin" +
      "g\030\005 \001(\010\022(\n\007options\030\006 \003(\0132\027.google.protob" +
      "uf.Option\022\'\n\006syntax\030\007 \001(\0162\027.google.proto" +
      "buf.Syntax\"#\n\005Mixin\022\014\n\004name\030\001 \001(\t\022\014\n\004roo" +
      "t\030\002 \001(\tBu\n\023com.google.protobufB\010ApiProto" +
      "P\001Z+google.golang.org/genproto/protobuf/" +
      "api;api\242\002\003GPB\252\002\036Google.Protobuf.WellKnow" +
      "nTypesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.SourceContextProto.getDescriptor(),
          com.google.protobuf.TypeProto.getDescriptor(),
        }, assigner);
    internal_static_google_protobuf_Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_Api_descriptor,
        new java.lang.String[] { "Name", "Methods", "Options", "Version", "SourceContext", "Mixins", "Syntax", });
    internal_static_google_protobuf_Method_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_protobuf_Method_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_Method_descriptor,
        new java.lang.String[] { "Name", "RequestTypeUrl", "RequestStreaming", "ResponseTypeUrl", "ResponseStreaming", "Options", "Syntax", });
    internal_static_google_protobuf_Mixin_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_protobuf_Mixin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_Mixin_descriptor,
        new java.lang.String[] { "Name", "Root", });
    com.google.protobuf.SourceContextProto.getDescriptor();
    com.google.protobuf.TypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
